name: Continuous Delivery

on:
  push:
    branches: [main]
    paths: ["hangman-api/**"]
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]

jobs:
  build:
    uses: ./.github/workflows/reusable-node-build.yaml
    with:
      node-version: 16
      working-directory: ./hangman-api
      artifact-name: build-code
  
  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Download artifact (dist folder)
        uses: actions/download-artifact@v4
        with:
          name: build-code
          path: hangman-api/dist/
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./hangman-api
          file: ./hangman-api/Dockerfile.workflow
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hangman-api-actions-2024:latest
      #- name: Build and push Docker image
      #  working-directory: ./hangman-api
      #  env:
      #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #    DOCKER_REPOSITORY: hangman-api-2024
      #  run: |
      #    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      #    image=$DOCKER_USERNAME/$DOCKER_REPOSITORY:$(date +%s)
      #    docker build -t $image -f Dockerfile.workflow .
      #    docker push $image
