on:
  push:
    branches: [main]
    paths: ["hangman-api/**"]
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code #optional
        uses : actions/checkout@v4   
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./hangman-api/package-lock.json
      - name : build
        working-directory: ./hangman-api
        run : |
          npm ci
          npm run build --if-present
      - name: Upload artifact (dist folder)
        uses: actions/upload-artifact@v4
        with:
          name: build-code
          path: hangman-api/dist/
  
  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Download artifact (dist folder)
        uses: actions/download-artifact@v4
        with:
          name: build-code
          path: hangman-api/dist/
      - name: Build Docker image
        working-directory: ./hangman-api
        run: docker build -t hangman-api-2024:$(date +%s) -f Dockerfile.workflow .
