name: CI

on:
  push:
    branches: [main]
    paths: ["hangman-api/**"]
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code #optional
        uses : actions/checkout@v4    
#      - name : setup node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
      - name : build
        working-directory: ./hangman-api
        run : |
          npm ci
          npm run build --if-present

  test:
    runs-on: ubuntu-latest
    steps: 
      - name : Checkout code #optional
        uses : actions/checkout@v4
      - name : build
        working-directory: ./hangman-api
        run : |
          npm ci
          npm test  