name: CI

on:
  push:
    branches: [main]
    paths: ["hangman-api/**"]
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code #optional
        uses : actions/checkout@v4   
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./hangman-api/package-lock.json
      - name : build
        working-directory: ./hangman-api
        run : |
          npm ci
          npm run build --if-present

  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name : Checkout code #optional
        uses : actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name : build
        working-directory: ./hangman-api
        run : | 
          npm ci
          npm test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code 
        uses : actions/checkout@v4
      - name : integration tests
        working-directory: ./hangman-api
        run: docker compose -f .\hangman-api\compose.integration.yml up --force-recreate --exit-code-from build-db-relationships
