name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code #optional
        uses : actions/checkout@v4        
      - name : build and test
        working-directory: ./hangman-api
        run : |
          npm ci
          npm run build --if-present
          npm test

        