name: CI - build artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code #optional
        uses : actions/checkout@v4    
      - name : build
        working-directory: ./hangman-api
        run : |
          npm ci
          npm run build --if-present
      - name : Upload artifact (dependencies)
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: hangman-api/node_modules
          include-hidden-files: true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name : Checkout code #optional
        uses : actions/checkout@v4
      - name : Download artifact (dependencies)
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: hangman-api/node_modules
      - name : build
        working-directory: ./hangman-api
        run : npm test    