name: hagman-e2e-ci
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ["hangman-e2e/**"]

jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: |
            ./hangman-api/package-lock.json
            ./hangman-front/package-lock.json

      - name : Start hangman-api
        working-directory: ./hangman-api
        run : |
          npm ci
          npm run start &

      - name : Start hangman-front
        working-directory: ./hangman-front
        run : |
          npm ci
          npm run start &

      - name: Test E2E
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./hangman-e2e/e2e
          wait-on: 'http://localhost:8080'   

      - name: Upload videos     
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: hangman-e2e/e2e/cypress/videos
          if-no-files-found: ignore          