name: hangman-front-ci
on:
  pull_request:
    branches: [main]
    paths: ["hangman-front/**"]

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./hangman-front/package-lock.json
      - name: Build
        working-directory: ./hangman-front
        run: |
          npm ci
          npm run build --if-present
  
  test-front:
    runs-on: ubuntu-latest
    needs: build-front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./hangman-front/package-lock.json
      - name: Test
        working-directory: ./hangman-front
        run: |
          npm ci
          npm test