name: Motivate on Label
on:
  issues:
    types: 
      - labeled

jobs:
  motivate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Motivational Message
        uses: franjfgcarmo/gh-lemon-code-motivational-message@v1.0.0