name: Test get coomodity price action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commodity: ['gold', 'silver', 'platinum']
        currency: ['USD', 'EUR', 'GBP']

    steps:
      - name: Test Get Commodity Price Action with silver
        uses: franjfgcarmo/get-commodity-price-action@v1.0.0
        with:
          commodity: ${{ matrix.commodity }}
          currency: ${{ matrix.currency }}